# Generated by Django 3.0.5 on 2020-04-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(verbose_name='ID Telegram')),
                ('username', models.CharField(max_length=250, verbose_name='Username de telegram')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del Usuario')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
