# Generated by Django 3.0.5 on 2020-04-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200418_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=250, null=True, verbose_name='Correo del Usuario'),
        ),
    ]
