# Generated by Django 3.0.5 on 2020-04-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=250, null=True, verbose_name='Telefono del Usuario'),
        ),
    ]
