# Generated by Django 3.0.5 on 2020-04-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='provincia',
            field=models.CharField(max_length=50, null=True, verbose_name='Povincia del Usuario'),
        ),
    ]
