# Generated by Django 3.0.5 on 2020-04-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_profile_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_3d',
            field=models.BooleanField(default=False, verbose_name='Tiene impresora'),
        ),
    ]
