# Generated by Django 3.0.5 on 2020-04-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_profile_is_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cant_fdm',
            field=models.IntegerField(default=0, verbose_name='Cantidad de impresoras FDM'),
        ),
    ]
